#!/usr/bin/env python3
"""
Pi Value World - Verification Script
Submit your calculation results for verification and certificate generation
"""

import json
import os
import sys
from datetime import datetime

# Try to import requests, provide helpful error if missing
try:
    import requests
except ImportError:
    print("❌ requests library not installed!")
    print("Please install it with: pip install requests")
    sys.exit(1)

def load_result_file():
    """Load the result file generated by piclalculation.py"""
    print("🔍 Looking for result files...\n")
    
    # Find all pi_result_*.json files in current directory
    result_files = [f for f in os.listdir('.') if f.startswith('pi_result_') and f.endswith('.json')]
    
    if not result_files:
        print("❌ No result files found!")
        print("Please run piclalculation.py first to generate your results.\n")
        return None
    
    if len(result_files) == 1:
        print(f"✅ Found result file: {result_files[0]}")
        with open(result_files[0], 'r') as f:
            return json.load(f)
    
    # Multiple files found
    print("Multiple result files found:")
    for i, file in enumerate(result_files, 1):
        print(f"{i}. {file}")
    
    while True:
        try:
            choice = int(input("\nSelect file number: "))
            if 1 <= choice <= len(result_files):
                with open(result_files[choice - 1], 'r') as f:
                    return json.load(f)
            print("Invalid choice!")
        except ValueError:
            print("Please enter a number!\n")

def submit_verification(data):
    """Submit verification data to Supabase"""
    # These will be configured from environment or user input
    supabase_url = os.getenv('PIVALUE_SUPABASE_URL', 'YOUR_SUPABASE_URL')
    supabase_key = os.getenv('PIVALUE_SUPABASE_KEY', 'YOUR_SUPABASE_KEY')
    
    if supabase_url == 'YOUR_SUPABASE_URL':
        print("\n⚠️  Supabase credentials not configured!")
        print("Please set the following environment variables:")
        print("  - PIVALUE_SUPABASE_URL")
        print("  - PIVALUE_SUPABASE_KEY")
        print("\nOr enter them manually below:\n")
        
        supabase_url = input("Enter Supabase URL: ").strip()
        supabase_key = input("Enter Supabase Key: ").strip()
    
    # Prepare submission data
    submission = {
        "github_username": data["github_username"],
        "verification_code": data["verification_code"],
        "submission_id": data["submission_id"],
        "time_limit": data["time_limit"],
        "calculations_performed": data["calculations_performed"],
        "precision_digits": data["precision_digits"],
        "elapsed_seconds": round(data["elapsed_seconds"], 2),
        "status": "pending",
        "submitted_at": datetime.now().isoformat()
    }
    
    print("\n📤 Submitting your verification...")
    print(f"👤 Username: {data['github_username']}")
    print(f"🎫 Code: {data['verification_code']}")
    print(f"🆔 ID: {data['submission_id']}")
    
    # In production, this would POST to Supabase
    # For now, save locally and show instructions
    print("\n" + "=" * 60)
    print("✅ Verification Data Ready!")
    print("=" * 60)
    
    # Save submission file
    submission_file = f"submission_{data['github_username']}.json"
    with open(submission_file, 'w') as f:
        json.dump(submission, f, indent=2)
    
    print(f"\n💾 Submission saved to: {submission_file}")
    
    print("\n📋 Next Steps:")
    print("1. Create a Pull Request with this submission file")
    print("2. Wait for maintainer approval")
    print("3. Once merged, visit the website to get your certificate!")
    print("\n🌐 Website: https://pivalue.world\n")
    
    # Show summary
    print("=" * 60)
    print("📊 Submission Summary:")
    print("=" * 60)
    print(f"GitHub Username: {data['github_username']}")
    print(f"Time Limit: {data['time_limit']} minute(s)")
    print(f"Calculations: {data['calculations_performed']}")
    print(f"Precision: {data['precision_digits']} decimal places")
    print(f"Status: ⏳ Pending Verification")
    print(f"\n🎫 Save this code: {data['verification_code']}")
    print(f"🆔 Save this ID: {data['submission_id']}\n")
    
    return submission

def manual_entry():
    """Allow manual entry of verification code and ID"""
    print("📝 Manual Verification Entry\n")
    
    while True:
        submission_id = input("Enter your Submission ID: ").strip()
        if submission_id:
            break
        print("ID cannot be empty!\n")
    
    while True:
        verification_code = input("Enter your Verification Code: ").strip()
        if verification_code:
            break
        print("Code cannot be empty!\n")
    
    github_username = input("Enter your GitHub username: ").strip()
    
    print("\n⚠️  Manual entry requires additional validation.")
    print("Please ensure you have your original result file.\n")
    
    return {
        "submission_id": submission_id,
        "verification_code": verification_code,
        "github_username": github_username
    }

def main():
    print("=" * 60)
    print("🥧 Pi Value World - Verification 🥧")
    print("=" * 60)
    print("\nSubmit your calculation results for verification\n")
    
    print("Choose verification method:")
    print("1. Use existing result file (Recommended)")
    print("2. Manual entry")
    
    choice = input("\nEnter choice (1/2): ").strip()
    
    if choice == '1':
        data = load_result_file()
        if not data:
            return
    elif choice == '2':
        data = manual_entry()
    else:
        print("❌ Invalid choice!")
        return
    
    # Submit verification
    submit_verification(data)
    
    print("\n✨ Thank you for your submission!")
    print("🔍 You can track your submission status on our website")
    print("🌐 https://pivalue.world/search\n")

if __name__ == "__main__":
    main()
